# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Jaeger_DView.ui'
#
# Created: Mon Nov  7 22:51:02 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1345, 531)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(320, 100, 1021, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.B5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B5.setObjectName("B5")
        self.gridLayout.addWidget(self.B5, 1, 0, 1, 1)
        self.B3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B3.setObjectName("B3")
        self.gridLayout.addWidget(self.B3, 0, 3, 1, 1)
        self.B10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B10.setObjectName("B10")
        self.gridLayout.addWidget(self.B10, 2, 0, 1, 1)
        self.B8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B8.setObjectName("B8")
        self.gridLayout.addWidget(self.B8, 1, 3, 1, 1)
        self.B6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B6.setObjectName("B6")
        self.gridLayout.addWidget(self.B6, 1, 1, 1, 1)
        self.B13 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B13.setObjectName("B13")
        self.gridLayout.addWidget(self.B13, 2, 3, 1, 1)
        self.B4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B4.setObjectName("B4")
        self.gridLayout.addWidget(self.B4, 0, 4, 1, 1)
        self.B14 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B14.setObjectName("B14")
        self.gridLayout.addWidget(self.B14, 2, 4, 1, 1)
        self.B0 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B0.setObjectName("B0")
        self.gridLayout.addWidget(self.B0, 0, 0, 1, 1)
        self.B9 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B9.setObjectName("B9")
        self.gridLayout.addWidget(self.B9, 1, 4, 1, 1)
        self.B7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B7.setObjectName("B7")
        self.gridLayout.addWidget(self.B7, 1, 2, 1, 1)
        self.B11 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B11.setObjectName("B11")
        self.gridLayout.addWidget(self.B11, 2, 1, 1, 1)
        self.B1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B1.setObjectName("B1")
        self.gridLayout.addWidget(self.B1, 0, 1, 1, 1)
        self.B2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B2.setObjectName("B2")
        self.gridLayout.addWidget(self.B2, 0, 2, 1, 1)
        self.B12 = QtGui.QPushButton(self.gridLayoutWidget)
        self.B12.setObjectName("B12")
        self.gridLayout.addWidget(self.B12, 2, 2, 1, 1)
        self.neu = QtGui.QPushButton(self.centralwidget)
        self.neu.setGeometry(QtCore.QRect(530, 430, 93, 28))
        self.neu.setObjectName("neu")
        self.Beenden = QtGui.QPushButton(self.centralwidget)
        self.Beenden.setGeometry(QtCore.QRect(1050, 430, 93, 28))
        self.Beenden.setObjectName("Beenden")
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(410, 20, 841, 71))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 0, 91, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 0, 91, 511))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.offenV = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.offenV.setText("")
        self.offenV.setObjectName("offenV")
        self.verticalLayout_2.addWidget(self.offenV)
        self.korrektV = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.korrektV.setText("")
        self.korrektV.setObjectName("korrektV")
        self.verticalLayout_2.addWidget(self.korrektV)
        self.falschV = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.falschV.setText("")
        self.falschV.setObjectName("falschV")
        self.verticalLayout_2.addWidget(self.falschV)
        self.gesamtV = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.gesamtV.setText("")
        self.gesamtV.setObjectName("gesamtV")
        self.verticalLayout_2.addWidget(self.gesamtV)
        self.spieleV = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.spieleV.setText("")
        self.spieleV.setObjectName("spieleV")
        self.verticalLayout_2.addWidget(self.spieleV)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.B5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.B3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.B10.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.B8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.B6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.B13.setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.B4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.B14.setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.B0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.B9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.B7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.B11.setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.B1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.B2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.B12.setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.neu.setText(QtGui.QApplication.translate("MainWindow", "Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.Beenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Drücken Sie die Buttons in aufsteigender Reihenfolge!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Offen:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Korrekt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Falsch:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Gesamt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Spiele:", None, QtGui.QApplication.UnicodeUTF8))

